export const products = [
  {
    //PC PORTABLES
    id: "1",
    name: "Hp Notbook 250 G9",
    description:
      "Processor:Intel Core Ultra 7 , RAM: DDR4, Storage:512GB SSD,14 Full HD ",
    price: 105000,
    originalPrice: 135000,
    images: [
      "/images/pc-portable/pc-hp.jpg",
      "/images/pc-portable/hp-rose.jpg",
      "/images/pc-portable/hp-noir.jpg",

     ],
    image: "/images/pc-portable/pc-hp.jpg",
    category: "pc_portable",
    isNew: true,
    isPromo: true,
    colors: ["Rose", "Noir", "Gris"],
    sizes: ["8GB","16GB"],  
  },
  {
    id: "2",
    name: "Dell Inspiron 15",
    description:
      "Processor:Intel Core i5 11e generation , RAM: DDR4, Storage:512GB SSD,Ecran:15 Full HD",
    price: 128000,
    images: ["/images/pc-portable/pc-dell.jpg",
        ],
    image: "/images/pc-portable/pc-dell.jpg",
    category: "pc_portable",
    isNew: true,
    colors: ["Noir"],
    sizes: ["8GB","16GB"],  
  },
  {
    id: "3",
    name: "Microsoft Surface ",
    description:
      "i7 12eme generation,16GB RAM,25GB SSD,3K tactile",
    price: 200000,
    images: [
      " /images/pc-portable/pc-microsoft.jpg",
      "/images/pc-portable/microsoft-rose.jpg",
      "/images/pc-portable/microsoft-noir.jpg",

      ],
    image: " /images/pc-portable/pc-microsoft.jpg",
    category: "pc_portable",
    isNew: true,
    colors: ["Noir", "Rose", "Gris"],
    sizes: [ "15pouce", "14pouce", "13pouce"],
  },
  {
    id: "4",
    name: "Apple Macbook Air 2022",
    description:
      "8GB,256GB SSD ,2K",
    price: 155000,
    originalPrice: 195000,
    images: [
    "/images/pc-portable/macos-gris.jpg",
    "/images/pc-portable/macos-rose.jpg",
    "/images/pc-portable/macos-noir.jpg",
    ],
    image: "/images/pc-portable/macos-gris.jpg",
    category: "pc_portable",
    isPromo: true,
    colors: ["Rose", "Noir", "Gris"],
    sizes: ["15 pouce", "14 pouce", "13 pouce"],
  },
  {
    //planners
    id: "5",
    name: "NoteBook",
    description:"cahier pratique pur prendre des notes en Cours,organiser ses idees et reviser efficacement .",
    price: 700,
    originalPrice: 1200,
    images: [
    "/images/planners/planner1.jpg"],
    image: "/images/planners/planner1.jpg",
    category: "planners",
    isPromo: true,
    colors: ["violet", "Rose", "vert"],
    sizes: ["unique"],
  },
  {
    id: "6",
    name: "My Planner ",
    description:
      "Planner Organiser pour planifier les journees,gerer le tempset atteindre ses objectifs.",
    price: 2000,
    images: [
      "/images/planners/planner2.jpg",
      "/images/planners/planner3.jpg",
      "/images/planners/planner5.jpg",
    ],
    image: "/images/planners/planner2.jpg",
    category: "planners",
    isNew: true,
    colors: ["Unique"],
    sizes: ["unique"],
  },
  {
    id: "7",
    name: "Agenda 2026",
    description:
      "Pratique pour organiser ses journees,noter les rendez-vous et gerer le temps toute l'annee.",
    price: 1200,
    images: [
      "/images/planners/planner4.jpg",
    ],
    image: "/images/planners/planner4.jpg",
    category: "planners",
    colors: ["Unique"],
    sizes: ["unique"],
  },
  {
    //affaires scolaires
    id: "8",
    name: "Graveuse",
    description:
      "simple et pratique,ideale pour les projets et les traveaux manuels.",
    price: 800,
    images: [
      "/images/affaires-scolaires/graveuse.jpg",
    ],
    image:  "/images/affaires-scolaires/graveuse.jpg",
    category: "affaires_scolaires",
    colors: ["Bleu", "Beige", "Roge"],
    sizes: ["unique"],
  },
  {
    id: "9",
    name: "Stylos",
    description: "stylos fluides et confortables pour une ecriture claire et agreable.",
    price: 1400,
    images: [
       "/images/affaires-scolaires/pens.jpg",
        "/images/affaires-scolaires/stylo.jpg",
    ],
    image:  "/images/affaires-scolaires/pens.jpg",
    category: "affaires_scolaires",
    isNew: true,
    colors: ["Unique"],
    sizes: ["unique"],
  },
  {
    id: "10",
    name: "Souligneurs ",
    description: "Ideals pour mettre en evidence les informatons importantes lors des reisions.",
    price: 1000,
    images: [
       "/images/affaires-scolaires/souligneurs.jpg",
     ],
    image:  "/images/affaires-scolaires/souligneurs.jpg",
    category: "affaires_scolaires",
    colors: ["vert", "Rose", "Bleu","jaune","violet","orange"],
    sizes: ["unique"],
  },
   {
    id: "11",
    name: "Sticky Notes ",
    description: "pour ne rien oblier .",
    price: 120,
    images: [
       "/images/affaires-scolaires/sticky-note.jpg",
       "/images/affaires-scolaires/sticky-notes.jpg",
       "/images/affaires-scolaires/sticky.jpg",
     ],
    image:  "/images/affaires-scolaires/sticky-note.jpg",
    category: "affaires_scolaires",
    colors: ["multicoleur"],
    sizes: ["moyen"],
  },
   {
    id: "12",
    name: "Port Bloc ",
    description: "support pratique ,solide pour prendre les notes rapidement.",
    price: 120,
    images: [
       "/images/affaires-scolaires/port bloc.jpg",
     ],
    image:  "/images/affaires-scolaires/port bloc.jpg",
    category: "affaires_scolaires",
    colors: ["Noir","blanc"],
    sizes: ["unique"],
  },
  {
    //cartables
    id: "13",
    name: "Sac a dos pc ",
    description: "sac a dos pratique et resistant pour transporter ton pc  et tes affaires en toute securite.",
    price: 4000,
    images: [
     "/images/cartables/sacados1.jpg",
      "/images/cartables/sacados2.jpg",
      "/images/cartables/sacados3.jpg",
     ],
    image: "/images/cartables/sacados1.jpg",
    category: "cartables",
    colors: ["Noir","gris"],
    sizes: ["unique"],
  },
  {
    id: "14",
    name: "Cache pc ",
    description: "proteger ton pc et ton elegance en meme temps .",
    price: 3200,
    images: [
     "/images/cartables/cachepc.jpg",
      "/images/cartables/cachepc2.jpg",
      "/images/cartables/cachepc3.jpg",
     ],
    image: "/images/cartables/cachepc.jpg",
    category: "cartables",
    colors: ["rose","vert","bleu","beige"],
    sizes: ["unique"],
  },
  {
    //calculatrices
    id: "15",
    name: "Calculatrice FX-92",
    description: "calculatrice scientifique ideale pour les cours de maths et les examens .",
    price: 3500,
    originalPrice:4000,
    images: [
     "/images/calculatrices/calculatrice4.jpg",
     ],
    image: "/images/calculatrices/calculatrice4.jpg",
    category: "calculatrices",
    isPromo:true,
    colors: ["unique"],
    sizes: ["unique"],
  },
{
    id: "16",
    name: "Calculatrice graphique",
    description: "calculatrice scientifique graphique affiches les graphs et les fonctions complexes facilement .",
    price: 4000,
    images: [
     "/images/calculatrices/calculatrice1.jpg",
     ],
    image: "/images/calculatrices/calculatrice1.jpg",
    category: "calculatrices",
    isNew:true,
    colors: ["unique"],
    sizes: ["unique"],
  },
  {
    id: "17",
    name: "Calculatrice casio",
    description: "calculatrice scientifique ideale pour les cours de maths et les examens .",
    price: 2500,
    originalPrice:3000,
    images: [
     "/images/calculatrices/calculatrice3.jpg",
     ],
    image: "/images/calculatrices/calculatrice3.jpg",
    category: "calculatrices",
    isPromo:true,
    colors: ["unique"],
    sizes: ["unique"],
  },
   {
    //accessoires technique
    id: "18",
    name: "Casque sans fil BLEUTOOTH",
    description: "casque audio confrtable avec son clair .",
    price: 4500,
    originalPrice:3500,
    images: [
     "/images/accessoires-technique/casque.jpg",
     "/images/accessoires-technique/casque-noir.jpg",
     ],
    image: "/images/accessoires-technique/casque.jpg",
    category: "accessoires_technique",
    isPromo:true,
    colors: ["Gris","Noir"],
    sizes: ["unique"],
  },
 {
    id: "19",
    name: "Airpods",
    description: "Ecouteurs sans fil pratiques avec autonomie longue duree et son de qualitee.",
    price: 1500,
    images: [
     "/images/accessoires-technique/airpods.jpg",
     "/images/accessoires-technique/airpods2.jpg",
     ],
    image: "/images/accessoires-technique/airpods2.jpg",
    category: "accessoires_technique",
    colors: ["unique"],
    sizes: ["unique"],
  },
   {
    id: "20",
    name: "Chargeur Iphone",
    description: "chargeur rapide parfait pour rester connecte toute la journee.",
    price: 1500,
    images: [
     "/images/accessoires-technique/chargeur.jpg",
     ],
    image: "/images/accessoires-technique/chargeur.jpg",
    category: "accessoires_technique",
    colors: ["unique"],
    sizes: ["unique"],
  },
   {
    id: "21",
    name: "Microphone",
    description: "ideal pour les cours en ligne, reunions ou enregistrenements vocaux.",
    price: 3000,
    images: [
     "/images/accessoires-technique/mic.jpg",
     ],
    image: "/images/accessoires-technique/mic.jpg",
    category: "accessoires_technique",
    isNew:true,
    colors: ["unique"],
    sizes: ["unique"],
  },
   {
    id: "22",
    name: "Power Bank",
    description: "Batterie Externe conpacte et puissante pour recharger smartphone et accessoires en deplacement.",
    price: 3000,
    images: [
     "/images/accessoires-technique/powerbanck.jpg",
     ],
    image: "/images/accessoires-technique/powerbanck.jpg",
    category: "accessoires_technique",
    colors: ["unique"],
    sizes: ["unique"],
  },
]


export const categoryNames = {
  pc_portable: "Ordinateurs portables",
  calculatrices: "Calculatrices",
  affaires_scolaires: "Affaires Scolaires",
  planners: "Planners & Agendas",
  cartables: "Sacs et Cartables",
  accessoires_technique: "Accessoires Techniques ",
}
