export const wilayas = [
  {
    code: "01",
    name: "Adrar",
    communes: [
      "Adrar",
      "Tamest",
      "Charouine",
      "Reggane",
      "In Zghmir",
      "Tit",
      "Ksar Kaddour",
      "Tsabit",
      "Timimoun",
      "Ouled Said",
      "Zaouiet Kounta",
      "Aoulef",
      "Timiaouine",
      "Tinerkouk",
      "Deldoul",
      "Sali",
      "Akabli",
      "Metarfa",
      "Ouled Aissa",
      "Bouda",
      "Aougrout",
      "Talmine",
      "Bordj Badji Mokhtar",
      "Sebaa",
      "Ouled Ahmed Timmi",
      "Fenoughil",
      "Tamantit",
      "Tindouf",
    ],
  },
  {
    code: "02",
    name: "Chlef",
    communes: [
      "Chlef",
      "Ténès",
      "Benairia",
      "El Karimia",
      "Tadjena",
      "Taougrit",
      "Beni Haoua",
      "Sobha",
      "Harchoun",
      "Ouled Fares",
      "Sidi Akkacha",
      "Boukadir",
      "Beni Rached",
      "Talassa",
      "Herenfa",
      "Oued Goussine",
      "Dahra",
      "Ouled Abbes",
      "Sendjas",
      "Zeboudja",
      "Oued Sly",
      "Abou El Hassen",
      "El Marsa",
      "Chettia",
      "Sidi Abderrahmane",
      "Moussadek",
      "El Hadjadj",
      "Labiod Medjadja",
      "Oued Rhiou",
      "Ouled Ben Abdelkader",
      "Bouzghaia",
      "Ain Merane",
      "Oum Drou",
      "Breira",
      "Beni Bouattab",
    ],
  },
  {
    code: "03",
    name: "Laghouat",
    communes: [
      "Laghouat",
      "Ksar El Hirane",
      "Bennasser Benchohra",
      "Sidi Makhlouf",
      "Hassi Delaa",
      "Hassi R'Mel",
      "Ain Madhi",
      "Tadjmout",
      "Kheneg",
      "Gueltat Sidi Saad",
      "Ain Sidi Ali",
      "Beidha",
      "Brida",
      "El Ghicha",
      "El Houaita",
      "Hadj Mechri",
      "Sebgag",
      "Taouiala",
      "Tadjrouna",
      "Aflou",
      "El Assafia",
      "Oued Morra",
      "Oued Mzi",
      "Sidi Bouzid",
    ],
  },
  {
    code: "04",
    name: "Oum El Bouaghi",
    communes: [
      "Oum El Bouaghi",
      "Ain Beida",
      "Ain M'Lila",
      "Behir Chergui",
      "El Amiria",
      "Sigus",
      "El Belala",
      "Ain Babouche",
      "Berriche",
      "Ouled Hamla",
      "Dhala",
      "Ain Kercha",
      "Hanchir Toumghani",
      "El Djazia",
      "Ain Diss",
      "Fkirina",
      "Souk Naamane",
      "Zorg",
      "El Fedjoudj Boughrara Saoudi",
      "Ouled Zouai",
      "Bir Chouhada",
      "Ksar Sbahi",
      "Oued Nini",
      "Meskiana",
      "Ain Fekroun",
      "Rahia",
      "Ain Zitoun",
      "Ouled Gacem",
      "El Harmilia",
    ],
  },
  {
    code: "05",
    name: "Batna",
    communes: [
      "Batna",
      "Ghassira",
      "Maafa",
      "Merouana",
      "Seriana",
      "Menaa",
      "El Madher",
      "Tazoult",
      "N'Gaous",
      "Guigba",
      "Inoughissen",
      "Ouyoun El Assafir",
      "Djerma",
      "Bitam",
      "Abdelkader",
      "Arris",
      "Kimmel",
      "Tilatou",
      "Ain Djasser",
      "Ouled Sellam",
      "Tigherghar",
      "Ain Yagout",
      "Fesdis",
      "Sefiane",
      "Rahbat",
      "Tighanimine",
      "Lemsane",
      "Ksar Bellezma",
      "Seggana",
      "Ichmoul",
      "Foum Toub",
      "Beni Foudhala El Hakania",
      "Oued El Ma",
      "Talkhamt",
      "Bouzina",
      "Chemora",
      "Oued Chaaba",
      "Taxlent",
      "Gosbat",
      "Ouled Aouf",
      "Boumagueur",
      "Barika",
      "Djezzar",
      "Tkout",
      "Ain Touta",
      "Hidoussa",
      "Teniet El Abed",
      "Oued Taga",
      "Ouled Fadel",
      "Timgad",
      "Ras El Aioun",
      "Chir",
      "Ouled Si Slimane",
      "Zanat El Beida",
      "M'Doukal",
      "Ouled Ammar",
      "El Hassi",
      "Lazrou",
      "Boumia",
      "Boulhilat",
      "Lemcen",
    ],
  },
  {
    code: "06",
    name: "Béjaïa",
    communes: [
      "Béjaïa",
      "Amizour",
      "Ferraoun",
      "Taourirt Ighil",
      "Chellata",
      "Tamokra",
      "Timezrit",
      "Souk El Tenine",
      "M'Cisna",
      "Tinebdar",
      "Tichy",
      "Semaoun",
      "Kendira",
      "Tifra",
      "Ighram",
      "Amalou",
      "Ighil Ali",
      "Fenaia",
      "Toudja",
      "Darguina",
      "Sidi Aich",
      "El Kseur",
      "Shabet El Ameur",
      "Tamridjet",
      "Adekar",
      "Akbou",
      "Seddouk",
      "Tazmalt",
      "Ait Rizine",
      "Chemini",
      "Souk Oufella",
      "Taskriout",
      "Tibane",
      "Tala Hamza",
      "Barbacha",
      "Beni Djellil",
      "Ouzellaguen",
      "Bouhamza",
      "Beni Ksila",
      "Oued Ghir",
      "Ighil Nacer",
      "Melbou",
      "Tamala",
      "Bouzeguene",
      "Kherrata",
      "Draa Kaid",
      "Tamokra",
      "Boudjellil",
      "Boukhelifa",
      "Tizi N'Berber",
      "Beni Melikeche",
      "Sidi Ayad",
    ],
  },
  {
    code: "07",
    name: "Biskra",
    communes: [
      "Biskra",
      "Sidi Okba",
      "Chubet El Ameur",
      "Mchouneche",
      "El Kantara",
      "Ain Naga",
      "Zeribet El Oued",
      "El Feidh",
      "Tolga",
      "Lioua",
      "Lichana",
      "Ouled Djellal",
      "Sidi Khaled",
      "M'Lili",
      "Mekhadma",
      "El Ghrous",
      "El Outaya",
      "Djemorah",
      "Ain Zaatout",
      "El Haouch",
      "Khenguet Sidi Nadji",
      "Ourlal",
      "Meziraa",
      "Bouchagroun",
      "M'Doukal",
      "Oumache",
      "Branis",
      "Hadjeb El Aioun",
      "Doucen",
      "Chaiba",
      "Besbes",
      "Foughala",
      "Ain Ben Noui",
    ],
  },
  {
    code: "08",
    name: "Béchar",
    communes: [
      "Béchar",
      "Kénadsa",
      "Lahmar",
      "Beni Ounif",
      "Taghit",
      "Beni Abbès",
      "El Ouata",
      "Ksabi",
      "Mougheul",
      "Lahmar",
      "Boukais",
      "Mogheul",
      "Tabelbala",
      "Igli",
      "Kerzaz",
      "Ksabi",
      "Timoudi",
      "Ouled Khoudir",
      "Boukais",
      "Abadla",
      "Béni Ikhlef",
      "Kénadsa",
    ],
  },
  {
    code: "09",
    name: "Blida",
    communes: [
      "Blida",
      "Chréa",
      "Boufarik",
      "Larbaa",
      "Oued Alleug",
      "Chiffa",
      "Hammam Melouane",
      "Ben Khelil",
      "Soumaa",
      "Mouzaia",
      "El Affroun",
      "Chebli",
      "Bouinan",
      "Oued El Alleug",
      "Ridane",
      "Djebabra",
      "Beni Tamou",
      "Bouarfa",
      "Beni Mered",
      "Bougara",
      "Guerrouaou",
      "Ain Romana",
      "Souhane",
      "Ouled Yaich",
    ],
  },
  {
    code: "10",
    name: "Bouira",
    communes: [
      "Bouira",
      "Aïn Bessem",
      "Bir Ghbalou",
      "Bouderbala",
      "El Hachimia",
      "Kadiria",
      "Lakhdaria",
      "M'Chedallah",
      "Sour El Ghouzlane",
      "Taghzout",
      "Ain El Hadjar",
      "Dirah",
      "Saharidj",
      "Souk El Khemis",
      "Haizer",
      "Oued El Berdi",
      "Ridane",
      "Djebahia",
      "Ain Turk",
      "Aghbalou",
      "Bechloul",
      "Chorfa",
      "El Adjiba",
      "Guerrouma",
      "Maala",
      "Mezdour",
      "Ouled Rached",
      "Raouraoua",
      "Taguedit",
      "Zbarbar",
      "Ain Laloui",
      "Bordj Okhriss",
      "El Hakimia",
      "El Khabouzia",
      "Hanif",
      "Hadjera Zerga",
      "Mamora",
      "Oued Dheb",
      "Taghit",
      "Ain El Turc",
      "Dechmia",
      "El Asnam",
      "Ahl El Ksar",
    ],
  },
  {
    code: "11",
    name: "Tamanrasset",
    communes: [
      "Tamanrasset",
      "Abalessa",
      "In Guezzam",
      "Tin Zaouatine",
      "Tazrouk",
      "In Salah",
      "In Amguel",
      "Foggaret Ezzaouia",
    ],
  },
  {
    code: "12",
    name: "Tébessa",
    communes: [
      "Tébessa",
      "Bir El Ater",
      "Cheria",
      "Stah Guentis",
      "El Aouinet",
      "Lahouidjbet",
      "Safsaf El Ouesra",
      "Hammamet",
      "Négrine",
      "Bir Mokadem",
      "El Kouif",
      "Morsott",
      "El Ogla",
      "Bir Dheheb",
      "El Houidjbet",
      "Ouenza",
      "El Ma Labiodh",
      "Boulhaf Dir",
      "Bekkaria",
      "Boukhadra",
      "Ouled Rebah",
      "Bir El Ater",
      "Ferkane",
      "Tlidjene",
      "El Meridj",
      "Ain Zerga",
      "El Mazraa",
      "Gorriguer",
    ],
  },
  {
    code: "13",
    name: "Tlemcen",
    communes: [
      "Tlemcen",
      "Mansourah",
      "Chetouane",
      "Nedroma",
      "Ghazaouet",
      "Remchi",
      "Beni Saf",
      "Ouled Mimoun",
      "Amieur",
      "Ain Tallout",
      "El Aricha",
      "Souani",
      "Djebala",
      "El Fehoul",
      "Sebdou",
      "Beni Boussaid",
      "Sidi Abdelli",
      "Tianet",
      "Bab El Assa",
      "Dar Yaghmoracen",
      "Fellaoucene",
      "Azails",
      "Sebbaa Chioukh",
      "Terni Beni Hediel",
      "Bensekrane",
      "Ain Nehala",
      "Hennaya",
      "Maghnia",
      "Hammam Boughrara",
      "Souahlia",
      "Msirda Fouaga",
      "Ain Fetah",
      "El Gor",
      "Ouled Riyah",
      "Ain Ghoraba",
      "Chetouane",
      "Marsa Ben M'Hidi",
      "Beni Khellad",
      "Sid Djillali",
      "Beni Semiel",
      "Ain Youcef",
      "Zahra",
      "Ain Kebira",
      "Ouled Ouechih",
      "Bouhlou",
      "Souk Tleta",
      "Sidi Medjahed",
      "Beni Ouarsous",
      "Terny Beni Hediel",
      "Honaine",
      "Tianet",
    ],
  },
  {
    code: "14",
    name: "Tiaret",
    communes: [
      "Tiaret",
      "Medroussa",
      "Ain Bouchekif",
      "Sidi Ali Mellal",
      "Ain Zarit",
      "Ain Deheb",
      "Sidi Bakhti",
      "Medrissa",
      "Zmalet El Emir Abdelkader",
      "Madna",
      "Sebt",
      "Mellakou",
      "Dahmouni",
      "Rahouia",
      "Mahdia",
      "Sougueur",
      "Sidi Abderrahmane",
      "Djillali Ben Amar",
      "Ain El Hadid",
      "Rechaiga",
      "Nadorah",
      "Tagdemt",
      "Oued Lilli",
      "Mechraa Safa",
      "Hamadia",
      "Chehaima",
      "Takhemaret",
      "Sidi Hosni",
      "Sebaine",
      "Tousnina",
      "Frenda",
      "Ain Kermes",
      "Ksar Chellala",
      "Meghila",
      "Madna",
      "Bougara",
      "Mellakou",
      "Chehaima",
      "Faidja",
      "Tidda",
      "Djebilet Rosfa",
      "Sidi Abdelghani",
    ],
  },
  {
    code: "15",
    name: "Tizi Ouzou",
    communes: [
      "Tizi Ouzou",
      "Ain El Hammam",
      "Akbil",
      "Freha",
      "Souama",
      "Mechtrass",
      "Irdjen",
      "Timizart",
      "Makouda",
      "Draa El Mizan",
      "Tizi Gheniff",
      "Bounouh",
      "Ait Chafaa",
      "Frikat",
      "Beni Aissi",
      "Beni Zmenzer",
      "Iferhounene",
      "Azazga",
      "Illoula Oumalou",
      "Yakouren",
      "Larbaâ Nait Irathen",
      "Tizi Rached",
      "Zekri",
      "Ouaguenoun",
      "Ain Zaouia",
      "M'Kira",
      "Ait Yahia",
      "Ait Mahmoud",
      "Maatkas",
      "Ait Boumehdi",
      "Abi Youcef",
      "Beni Douala",
      "Illilten",
      "Bouzeguene",
      "Ait Aggouacha",
      "Ouadhias",
      "Azeffoun",
      "Tigzirt",
      "Ait Aissa Mimoun",
      "Boghni",
      "Ifigha",
      "Ait Oumalou",
      "Tirmitine",
      "Akerrou",
      "Yatafen",
      "Beni Ziki",
      "Draâ Ben Khedda",
      "Ouacif",
      "Idjeur",
      "Mekla",
      "Tizi N'Tleta",
      "Ait Yenni",
      "Aghribs",
      "Iflissen",
      "Boudjima",
      "Ait Yahia Moussa",
      "Souk El Tenine",
      "Ait Khelili",
      "Sidi Naamane",
      "Iboudraren",
      "Agouni Gueghrane",
    ],
  },
  {
    code: "16",
    name: "Alger",
    communes: [
      "Alger Centre",
      "Sidi M'Hamed",
      "El Madania",
      "Hamma El Annasser",
      "Bab El Oued",
      "Bologhine",
      "Casbah",
      "Oued Koriche",
      "Bir Mourad Rais",
      "El Biar",
      "Bouzareah",
      "Birkhadem",
      "El Harrach",
      "Baraki",
      "Oued Smar",
      "Boumerdes",
      "Bachdjerrah",
      "Hussein Dey",
      "Kouba",
      "Bourouba",
      "Dar El Beida",
      "Bab Ezzouar",
      "Ben Aknoun",
      "Dely Ibrahim",
      "Hammamet",
      "Rais Hamidou",
      "Djasr Kasentina",
      "El Mouradia",
      "Hydra",
      "Mohammadia",
      "Bordj El Kiffan",
      "El Magharia",
      "Beni Messous",
      "Les Eucalyptus",
      "Birtouta",
      "Tessala El Merdja",
      "Ouled Chebel",
      "Sidi Moussa",
      "Ain Taya",
      "Bordj El Bahri",
      "El Marsa",
      "H'raoua",
      "Rouiba",
      "Reghaïa",
      "Ain Benian",
      "Staoueli",
      "Zeralda",
      "Mahelma",
      "Rahmania",
      "Souidania",
      "Cheraga",
      "Ouled Fayet",
      "El Achour",
      "Draria",
      "Douera",
      "Baba Hassen",
      "Khraicia",
      "Saoula",
    ],
  },
  {
    code: "17",
    name: "Djelfa",
    communes: [
      "Djelfa",
      "Moudjbara",
      "El Guedid",
      "Hassi Bahbah",
      "Ain Maabed",
      "Sed Rahal",
      "Faidh El Botma",
      "Birine",
      "Bouira Lahdab",
      "Zaccar",
      "El Khemis",
      "Sidi Baizid",
      "Mliliha",
      "El Idrissia",
      "Douis",
      "Hassi El Euch",
      "Messaad",
      "Guettara",
      "Sidi Ladjel",
      "Had Sahary",
      "Guernini",
      "Selmana",
      "Ain Chouhada",
      "Oum Laadham",
      "Deldoul",
      "Zaafrane",
      "Benhar",
      "Hassi Fedoul",
      "Ain El Ibel",
      "Tadmit",
      "El Charef",
      "Benyagoub",
      "Dar Chioukh",
    ],
  },
  {
    code: "18",
    name: "Jijel",
    communes: [
      "Jijel",
      "Eraguene",
      "El Aouana",
      "Ziama Mansouria",
      "Taher",
      "Emir Abdelkader",
      "Chekfa",
      "Chahna",
      "El Milia",
      "Sidi Maarouf",
      "Settara",
      "El Ancer",
      "Sidi Abdelaziz",
      "Kaous",
      "Ghebala",
      "Bouraoui Belhadef",
      "Djimla",
      "Selma Benziada",
      "Boussif Ouled Askeur",
      "El Kennar Nouchfi",
      "Ouled Yahia Khadrouche",
      "Boudria Beniyadjis",
      "Kemir Oued Adjoul",
      "Texenna",
      "Djemaa Beni Habibi",
      "Bordj Tahar",
      "Ouled Rabah",
      "Ouadjana",
    ],
  },
  {
    code: "19",
    name: "Sétif",
    communes: [
      "Sétif",
      "Ain El Kebira",
      "Beni Aziz",
      "Ouled Sidi Ahmed",
      "Boutaleb",
      "Ain Sebt",
      "Hammam Soukhna",
      "Ain Roua",
      "Draa Kebila",
      "Bir Haddada",
      "El Eulma",
      "Djemila",
      "Beni Ouartilane",
      "Rosfa",
      "Ouled Tebben",
      "Hamma",
      "Maaouia",
      "Ain Lahdjar",
      "Ksar El Abtal",
      "Beni Chebana",
      "Ouled Sabor",
      "Guenzet",
      "Mezloug",
      "Bazer Sakhra",
      "Hammam Guergour",
      "Ait Naoual Mezada",
      "Bougaa",
      "Bordj Bou Arreridj",
      "El Hassi",
      "Tala Ifacene",
      "Beni Fouda",
      "Tachouda",
      "Beidha Bordj",
      "El Ouldja",
      "Tizi N'Bechar",
      "Ouled Addouane",
      "Serdj El Ghoul",
      "Harbil",
      "El Ouricia",
      "Talaifacene",
      "Hamma Bouziane",
      "Babor",
      "Guidjel",
      "Ain Abessa",
      "Dehamcha",
      "Babor",
      "Salah Bey",
      "Ain Oulmene",
      "Hammam Sokhna",
      "Beni Hocine",
      "Taya",
      "Bougaa",
      "Ouled Si Ahmed",
      "Guelta Zerka",
      "Ain Arnat",
      "Amoucha",
      "Ain Legradj",
      "Ait Tizi",
      "Maouaklane",
    ],
  },
  {
    code: "20",
    name: "Saïda",
    communes: [
      "Saïda",
      "Doui Thabet",
      "Ain El Hadjar",
      "Ouled Khaled",
      "Moulay Larbi",
      "Youb",
      "Hounet",
      "Sidi Amar",
      "Sidi Boubekeur",
      "El Hassasna",
      "Maamora",
      "Sidi Yacoub",
      "Ouled Brahim",
      "Tircine",
      "Ain Soltane",
      "Ouled Kada Belhadj",
    ],
  },
  {
    code: "21",
    name: "Skikda",
    communes: [
      "Skikda",
      "Ain Zouit",
      "El Hadaiek",
      "Azzaba",
      "Djendel Saadi Mohamed",
      "Ain Charchar",
      "Bekkouche Lakhdar",
      "Benazouz",
      "Es Sebt",
      "Collo",
      "Cheraia",
      "Kerkera",
      "Ouled Attia",
      "Oued Zhour",
      "Zitouna",
      "El Arrouch",
      "Salah Bouchaour",
      "Tamalous",
      "Ain Bouziane",
      "Ramdane Djamel",
      "Beni Oulbane",
      "Fil Fila",
      "Hammadi Krouma",
      "Sidi Mezghiche",
      "Emjez Edchich",
      "Beni Bachir",
      "Kanoua",
      "El Ghedir",
      "Bouchtata",
      "Oum Toub",
      "Ain Kechra",
      "Hamadi Krouma",
      "Khenag Maoune",
      "Es Sebt",
      "Ouldja Boulbalout",
      "Beni Zid",
      "Kerkera",
      "Ouled Habbaba",
    ],
  },
  {
    code: "22",
    name: "Sidi Bel Abbès",
    communes: [
      "Sidi Bel Abbès",
      "Tessala",
      "Sidi Brahim",
      "Mostefa Ben Brahim",
      "Sfisef",
      "Ain Thrid",
      "Merine",
      "Ras El Ma",
      "Amarnas",
      "Tilmouni",
      "Sidi Lahcene",
      "Ain El Berd",
      "Moulay Slissen",
      "Souahlia",
      "Sidi Ali Boussidi",
      "Badredine El Mokrani",
      "Marhoum",
      "Tafissour",
      "Makedra",
      "Tenira",
      "Moulay Slissen",
      "Sidi Khaled",
      "Ain Tindamine",
      "Hassi Zahana",
      "Tabia",
      "Merine",
      "Dhaya",
      "Zoubia",
      "Ain Adden",
      "Ain Kada",
      "Sidi Yacoub",
      "Lamtar",
      "Oued Sefioun",
      "Ain Trid",
      "Ben Badis",
      "Sehala Thaoura",
      "Ain Thrid",
      "Hassi Dahou",
      "Oued Taourira",
      "Telagh",
      "Mezaourou",
      "Boukhanefis",
      "Chetouane Belaila",
      "Mostefa Ben Brahim",
      "Belarbi",
      "Ain Tindamine",
      "Hassi Zehana",
      "Redjem Demouche",
      "Bir El Hammam",
      "Sidi Brahim",
      "Hassi Dahou",
      "Ras El Ma",
    ],
  },
  {
    code: "23",
    name: "Annaba",
    communes: [
      "Annaba",
      "Berrahal",
      "El Hadjar",
      "Sidi Amar",
      "Seraidi",
      "El Bouni",
      "Treat",
      "Ain Berda",
      "Cheurfa",
      "El Eulma",
      "Oued El Aneb",
      "Chetaibi",
    ],
  },
  {
    code: "24",
    name: "Guelma",
    communes: [
      "Guelma",
      "Bouchegouf",
      "Nechmaya",
      "Roknia",
      "Ras El Agba",
      "Ain Ben Beida",
      "Khezaras",
      "Houari Boumediene",
      "Medjez Amar",
      "Bordj Sabath",
      "Ain Makhlouf",
      "Heliopolis",
      "Ain Larbi",
      "Fedjoudj",
      "Belkheir",
      "Sellaoua Announa",
      "Hammam Debagh",
      "Oued Zenati",
      "Tamlouka",
      "Ain Hessainia",
      "Khezaras",
      "Medjez Sfa",
      "Boumahra Ahmed",
      "Ain Ben Beida",
      "Bouati Mahmoud",
      "Nechmaya",
      "Dahouara",
      "Hammam N'Bail",
      "Oued Fragha",
      "El Fedjoudj",
      "Beni Mezline",
      "Hammam Debagh",
      "Guelaat Bou Sbaa",
      "Medjez Amar",
      "Ain Sandel",
    ],
  },
  {
    code: "25",
    name: "Constantine",
    communes: [
      "Constantine",
      "Hamma Bouziane",
      "Didouche Mourad",
      "El Khroub",
      "Ain Smara",
      "Ouled Rahmoun",
      "Zighoud Youcef",
      "Beni Hamiden",
      "El Meridj",
      "Ibn Ziad",
      "Messaoud Boudjeriou",
      "Ben Badis",
      "Ain Abid",
    ],
  },
  {
    code: "26",
    name: "Médéa",
    communes: [
      "Médéa",
      "Ouzera",
      "Ain Boucif",
      "Ouamri",
      "Sidi Naamane",
      "Tablat",
      "Chellalet El Adhaoura",
      "Bir Ben Laabed",
      "El Azizia",
      "Souagui",
      "Boughezoul",
      "Draa Essamar",
      "Tamesguida",
      "El Omaria",
      "Ksar El Boukhari",
      "Ouled Antar",
      "Ain Ouksir",
      "Cheniguel",
      "Ain Boucif",
      "Berrouaghia",
      "Seghouane",
      "Sidi Zahar",
      "Sidi Demed",
      "Mihoub",
      "Maghraoua",
      "Tafraout",
      "Chelalet El Adhaoura",
      "Oued Harbil",
      "Hannacha",
      "Khams Djouamaa",
      "Sidi Rabie",
      "Saneg",
      "El Hamdania",
      "Boghar",
      "Ain Ouksir",
      "Aziz",
      "Ouled Bouachra",
      "Ouled Hellal",
      "Tizi Mahdi",
      "Zoubiria",
      "Beni Slimane",
      "Bouaiche",
      "El Guelbelkebir",
      "Ain Boucif",
      "Derrag",
      "Sidi Naamane",
      "Ouled Deide",
      "Rebaia",
      "Oued Harbil",
      "Ouled Emaaraf",
      "Ouled Brahim",
      "Sedraia",
      "Bouchrahil",
      "Oum El Djellil",
      "El Ouinet",
      "Sidi Zahar",
      "Tablat",
      "Ain Ouksir",
      "Ouled Antar",
      "Chellalet El Adhaoura",
      "Tamesguida",
      "Kef Lakhdar",
      "El Haoudane",
      "Hannacha",
    ],
  },
  {
    code: "27",
    name: "Mostaganem",
    communes: [
      "Mostaganem",
      "Sayada",
      "Fornaka",
      "Stidia",
      "Ain Nouissy",
      "Hassi Mameche",
      "Ain Tadles",
      "Sour",
      "Oued El Kheir",
      "Sidi Ali",
      "Kheir Eddine",
      "Sidi Lakhdar",
      "Tazgait",
      "Stidia",
      "Bouguirat",
      "Sirat",
      "Ain Boudinar",
      "Mesra",
      "Mazagran",
      "Nekmaria",
      "Oued El Kheir",
      "Achaacha",
      "Khadra",
      "Nekmaria",
      "Touahria",
      "Sidi Belattar",
      "El Matmar",
      "Mansourah",
      "Souaflia",
      "Djaafra",
      "Sour",
      "Bouguirat",
      "Abdelmalek Ramdane",
      "Ain Sidi Cherif",
      "El Hassiane",
      "Mesra",
    ],
  },
  {
    code: "28",
    name: "M'Sila",
    communes: [
      "M'Sila",
      "Magra",
      "Hammam Dalaa",
      "Ouled Madhi",
      "Tarmount",
      "Khoubana",
      "Mcif",
      "Chellal",
      "Ain El Hadjel",
      "Ain El Melh",
      "Ouled Derradj",
      "Sidi Ameur",
      "Tamsa",
      "Ben Srour",
      "Mohamed Boudiaf",
      "Ouled Slimane",
      "El Houamed",
      "Hammam Dalaa",
      "Ain Khadra",
      "Graish",
      "Ouled Mansour",
      "Maadid",
      "Slim",
      "Khettouti Sed Eldjir",
      "Zarzour",
      "Bir Foda",
      "Djelal",
      "Ain Farès",
      "Sidi Hadjeres",
      "Souamaa",
      "Bou Saada",
      "Ouled Sidi Brahim",
      "Sidi Aissa",
      "Debila",
      "Maarif",
      "Menaa",
      "Berhoum",
      "Bouti Sayeh",
      "Ouled Addi Guebala",
      "Magra",
      "Sidi M'Hamed",
      "Ain El Hadjel",
      "Ouled Sliman",
      "El Hamel",
      "Roued",
      "Ouanougha",
      "Chellal",
      "Khoubana",
      "Ain Errich",
      "Benzouh",
      "Hammam Dalaa",
      "Ouled Madhi",
    ],
  },
  {
    code: "29",
    name: "Mascara",
    communes: [
      "Mascara",
      "Bouhanifia",
      "Tighennif",
      "Oued El Abtal",
      "Ain Ferah",
      "Alaimia",
      "Sidi Kada",
      "Zelamta",
      "Oued Taria",
      "Sidi Abdelmoumene",
      "Sig",
      "Hachem",
      "Mohammadia",
      "Sidi Abdeldjebar",
      "Ras Ain Amirouche",
      "El Bordj",
      "Ain Fekan",
      "Ghriss",
      "Maoussa",
      "Froha",
      "Ferme",
      "Ain Fares",
      "Khalouia",
      "El Menaouer",
      "Oued El Abtal",
      "Chorfa",
      "Sidi Boussaid",
      "Benian",
      "El Gaada",
      "Aouf",
      "Sehailia",
      "Matemore",
      "Makda",
      "Oggaz",
      "El Keurt",
      "Guerdjoum",
      "Nesmoth",
      "Sidi Abdelmoumen",
      "Ain Frass",
      "El Ghomri",
      "Bou Henni",
      "El Hachem",
      "Sedjerara",
      "Tizi",
      "Rio Salado",
      "Ain Ferah",
    ],
  },
  {
    code: "30",
    name: "Ouargla",
    communes: [
      "Ouargla",
      "N'Goussa",
      "Hassi Messaoud",
      "Rouissat",
      "Ain Beida",
      "Sidi Khouiled",
      "Hassi Ben Abdallah",
      "Tebesbest",
      "Touggourt",
      "Zaouia El Abidia",
      "El Alia",
      "Taibet",
      "Mnaguer",
      "Blidet Amor",
      "Sidi Slimane",
      "El Borma",
      "Hassi Messaoud",
      "Ouargla",
      "Rouissat",
      "Ain Beida",
    ],
  },
  {
    code: "31",
    name: "Oran",
    communes: [
      "Oran",
      "Gdyel",
      "Bir El Djir",
      "Hassi Bounif",
      "Es Senia",
      "Arzew",
      "Bethioua",
      "Marsat El Hadjadj",
      "Ain Turk",
      "El Ançor",
      "Oued Tlelat",
      "Tafraoui",
      "Sidi Chami",
      "Boufatis",
      "Mers El Kebir",
      "Bousfer",
      "El Karma",
      "Hassi Ben Okba",
      "Ben Freha",
      "Hassi Mefsoukh",
      "Sidi Ben Yebka",
      "Messerghin",
      "Boutlelis",
      "Ain El Kerma",
      "Ain Biya",
      "Hassi Bounif",
    ],
  },
  {
    code: "32",
    name: "El Bayadh",
    communes: [
      "El Bayadh",
      "Rogassa",
      "Stitten",
      "Brezina",
      "Ghassoul",
      "Bougtob",
      "El Kheither",
      "Kef El Ahmar",
      "Chellala",
      "Ain El Orak",
      "Arbaouat",
      "Bougtoub",
      "El Mehara",
      "Tousmouline",
      "Sidi Amar",
      "Sidi Slimane",
      "Sidi Taifour",
      "Boualem",
      "El Biodh",
      "Cheguig",
      "El Abiodh Sidi Cheikh",
      "Ain Adden",
    ],
  },
  {
    code: "33",
    name: "Illizi",
    communes: ["Illizi", "Djanet", "Debdeb", "Bordj Omar Driss", "In Amenas"],
  },
  {
    code: "34",
    name: "Bordj Bou Arréridj",
    communes: [
      "Bordj Bou Arreridj",
      "Ras El Oued",
      "Bordj Zemoura",
      "Mansourah",
      "Medjana",
      "Teniet En Nasr",
      "Jaafra",
      "El Hamadia",
      "Ain Tesra",
      "Bordj Ghedir",
      "Sidi Embarek",
      "Ouled Brahem",
      "Ouled Dahmane",
      "Haraza",
      "Ghilassa",
      "Rabta",
      "Ouled Sidi Brahim",
      "Tixter",
      "El Achir",
      "Ain Taghrout",
      "Bordj Bou Arreridj",
      "Colla",
      "Taglait",
      "Belimour",
      "Djaafra",
      "El Main",
      "Ouled Dahmane",
      "Khelil",
      "Tassamert",
      "El Euch",
      "Ksour",
      "Mardjat",
      "Bendaoud",
      "Hasnaoua",
      "El M'Hir",
    ],
  },
  {
    code: "35",
    name: "Boumerdès",
    communes: [
      "Boumerdes",
      "Boudouaou",
      "Afir",
      "Bordj Menaiel",
      "Baghlia",
      "Sidi Daoud",
      "Naciria",
      "Djinet",
      "Isser",
      "Zemmouri",
      "Si Mustapha",
      "Tidjelabine",
      "Chabet El Ameur",
      "Thenia",
      "Timezrit",
      "Corso",
      "Ouled Moussa",
      "Larbatache",
      "Bouzegza Keddara",
      "Taourga",
      "Ouled Heddadj",
      "Leghata",
      "Beni Amrane",
      "Souk El Had",
      "Boudouaou El Bahri",
      "Ouled Aissa",
      "Ben Choud",
      "Dellys",
      "Ammal",
      "Ain Legradj",
      "Hammedi",
      "Khemis El Khechna",
      "Laghouat",
    ],
  },
  {
    code: "36",
    name: "El Tarf",
    communes: [
      "El Tarf",
      "Bouhadjar",
      "Ben M'Hidi",
      "Boutheldja",
      "El Aioun",
      "Souarekh",
      "Ain El Assel",
      "Zerizer",
      "Zitouna",
      "Ain Kerma",
      "Oued Zitoun",
      "Hammam Beni Salah",
      "Echatt",
      "Besbes",
      "Asfour",
      "Cheffia",
      "Drean",
      "Chihani",
      "El Kala",
      "Raml Souk",
      "Lac des Oiseaux",
      "Bouteldja",
      "Chefia",
      "Hammam Beni Salah",
    ],
  },
  {
    code: "37",
    name: "Tindouf",
    communes: ["Tindouf", "Oum El Assel"],
  },
  {
    code: "38",
    name: "Tissemsilt",
    communes: [
      "Tissemsilt",
      "Bordj Bou Naama",
      "Theniet El Had",
      "Lazharia",
      "Beni Chaib",
      "Lardjem",
      "Melaab",
      "Sidi Lantri",
      "Bordj El Emir Abdelkader",
      "Layoune",
      "Khemisti",
      "Ouled Bessem",
      "Ammari",
      "Youssoufia",
      "Sidi Boutouchent",
      "Tiberkanine",
      "Ain Kermes",
      "Sidi Abed",
      "Tamalaht",
      "Sidi Slimane",
      "Boucaid",
    ],
  },
  {
    code: "39",
    name: "El Oued",
    communes: [
      "El Oued",
      "Robbah",
      "Oued El Alenda",
      "Bayadha",
      "Nakhla",
      "Guemar",
      "Kouinine",
      "Reguiba",
      "Hamraia",
      "Taghzout",
      "Debila",
      "Hassani Abdelkrim",
      "Hassi Khalifa",
      "Trifaoui",
      "Magrane",
      "Beni Guecha",
      "Ourmes",
      "Still",
      "Taleb Larbi",
      "Douar El Ma",
      "Sidi Aoun",
      "Tamerdjit",
      "Tendla",
      "El Ogla",
      "Mih Ouansa",
      "El M'Ghair",
      "Djamaa",
      "Sidi Amrane",
      "Oum Touyour",
      "Sidi Khellil",
    ],
  },
  {
    code: "40",
    name: "Khenchela",
    communes: [
      "Khenchela",
      "Mtoussa",
      "Kais",
      "Baghai",
      "El Hamma",
      "Ain Touila",
      "Taouzianat",
      "Bouhmama",
      "El Oueldja",
      "Remila",
      "Cherchar",
      "Djellal",
      "Babar",
      "Tamza",
      "Ensigha",
      "Ouled Rechache",
      "El Mahmal",
      "Msara",
      "Yabous",
      "Khirane",
      "Chelia",
    ],
  },
  {
    code: "41",
    name: "Souk Ahras",
    communes: [
      "Souk Ahras",
      "Sedrata",
      "Hanancha",
      "Taoura",
      "Drea",
      "Heddada",
      "Ain Soltane",
      "Ain Zana",
      "Ouled Driss",
      "Machroha",
      "Ouled Moumen",
      "Bir Bouhouche",
      "Safel El Ouiden",
      "Mdaourouche",
      "Oum El Adhaim",
      "Ain Kercha",
      "Terraguelt",
      "Zaarouria",
      "Tiffech",
      "Merahna",
      "Ouled Kebila",
      "Sidi Fredj",
      "Ragouba",
      "Khemissa",
      "Ouillen",
      "M'Daourouch",
    ],
  },
  {
    code: "42",
    name: "Tipaza",
    communes: [
      "Tipaza",
      "Menaceur",
      "Larhat",
      "Douaouda",
      "Bourkika",
      "Khemisti",
      "Aghabal",
      "Hedjout",
      "Sidi Ghiles",
      "Messelmoun",
      "Sidi Amar",
      "Gouraya",
      "Nadour",
      "Damiette",
      "Meurad",
      "Fouka",
      "Bou Ismail",
      "Ahmer El Ain",
      "Bou Haroun",
      "Sidi Semiane",
      "Ain Tagourait",
      "Kolea",
      "Chaiba",
      "Attatba",
      "Sidi Rached",
      "Bourkika",
      "Hadjout",
      "Meurad",
    ],
  },
  {
    code: "43",
    name: "Mila",
    communes: [
      "Mila",
      "Ferdjioua",
      "Chelghoum Laid",
      "Oued Athmenia",
      "Ain Mellouk",
      "Telerghma",
      "Oued Seguen",
      "Tadjenanet",
      "Benyahia Abderrahmane",
      "Ain Tine",
      "El Mechira",
      "Hamala",
      "Rouached",
      "Tessala Lamtai",
      "Grarem Gouga",
      "Sidi Merouane",
      "Chigara",
      "Zeghaia",
      "Ain Beida Harriche",
      "Ouled Khalouf",
      "Terrai Bainen",
      "Bouhatem",
      "Yahia Beniguecha",
      "Tiberguent",
      "Ain Mellouk",
      "Derrahi Bousselah",
      "Ahmed Rachedi",
      "Ouled Hamla",
      "Elayadi Barbes",
      "Sidi Khelifa",
      "Minar Zarza",
      "Amira Arres",
      "Tassadane Haddada",
      "Derradji Bousselah",
      "Bouhatem",
    ],
  },
  {
    code: "44",
    name: "Aïn Defla",
    communes: [
      "Ain Defla",
      "Miliana",
      "Boumedfaa",
      "Khemis Miliana",
      "Hammam Righa",
      "Arib",
      "Djelida",
      "El Amra",
      "Bourached",
      "El Karimia",
      "El Abadia",
      "Hoceinia",
      "Barbouche",
      "Djendel",
      "Oued Chorfa",
      "Ain Lechiakh",
      "Oued Djemaa",
      "Rouina",
      "Zeddine",
      "El Maain",
      "Tacheta Zegagha",
      "Bir Ould Khelifa",
      "Ben Allal",
      "Ain Bouyahia",
      "El Hassania",
      "Tiberkanine",
      "Belaas",
      "Ain Torki",
      "Sidi Lakhdar",
      "Bordj Emir Khaled",
      "Tarik Ibn Ziad",
      "Ain Sultan",
      "Bir Ould Khelifa",
      "Bathia",
      "Oued Fodda",
      "Mekhatria",
      "Djemaa Ouled Cheikh",
      "Ain Benian",
    ],
  },
  {
    code: "45",
    name: "Naâma",
    communes: [
      "Naama",
      "Mecheria",
      "Ain Sefra",
      "Tiout",
      "Sfissifa",
      "Moghrar",
      "Assela",
      "Djeniane Bourzeg",
      "Ain Ben Khelil",
      "Makman Ben Amer",
      "Kasdir",
      "El Biod",
    ],
  },
  {
    code: "46",
    name: "Aïn Témouchent",
    communes: [
      "Ain Temouchent",
      "Chaabet El Ham",
      "Ain Kihal",
      "Hammam Bouhadjar",
      "Beni Saf",
      "Ouled Boudjemaa",
      "Aghlal",
      "Terga",
      "Ain Tolba",
      "El Malah",
      "Sidi Ben Adda",
      "El Amria",
      "Hassi El Ghella",
      "Hassasna",
      "Tamzoura",
      "Chentouf",
      "Sidi Boumediene",
      "Oued Berkeche",
      "Oulhaca El Gheraba",
      "Bou Zedjar",
      "Zaouia",
      "Ain El Arbaa",
      "El Emir Abdelkader",
      "Sidi Safi",
      "Ouled Kihal",
      "Aoubellil",
      "Tamzoura",
    ],
  },
  {
    code: "47",
    name: "Ghardaïa",
    communes: [
      "Ghardaia",
      "El Menia",
      "Dhayet Ben Dhahoua",
      "Berriane",
      "Metlili",
      "El Guerrara",
      "El Atteuf",
      "Zelfana",
      "Sebseb",
      "Bounoura",
      "Hassi Fehal",
      "Hassi El Gara",
      "Mansoura",
    ],
  },
  {
    code: "48",
    name: "Relizane",
    communes: [
      "Relizane",
      "Oued Rhiou",
      "Belaassel Bouzegza",
      "Sidi Saada",
      "Ouled Aissa",
      "Sidi Lazreg",
      "El Hassi",
      "Sidi M'Hamed Benaouda",
      "Mediouna",
      "Sidi Khettab",
      "Ammi Moussa",
      "El Matmar",
      "Sidi M'Hamed Benali",
      "Mendes",
      "Zemmoura",
      "Beni Dergoun",
      "Djidiouia",
      "El Guettar",
      "Hamri",
      "Mazouna",
      "Kalaa",
      "Ain Rahma",
      "Yellel",
      "Oued Essalem",
      "Ouarizane",
      "Lahlef",
      "Beni Zentis",
      "Souk El Haad",
      "Ramka",
      "Bendaoud",
      "El Ouldja",
      "Merdja Sidi Abed",
      "Ouled Sidi Mihoub",
      "Had Echkalla",
      "Ain Tarek",
      "Sidi Saada",
      "Dar Ben Abdelah",
      "Bouzegza Keddara",
    ],
  },
  {
    code: "49",
    name: "Timimoun",
    communes: [
      "Timimoun",
      "Ouled Said",
      "Tinerkouk",
      "Deldoul",
      "Metarfa",
      "Talmine",
      "Ksar Kaddour",
      "Reggane",
      "Sali",
      "In Zghmir",
      "Aougrout",
      "Charouine",
      "Tsabit",
      "Adrar",
      "Fenoughil",
      "Tamantit",
      "Tamest",
      "Aoulef",
      "Timiaouine",
      "Zaouiet Kounta",
      "Akabli",
      "Ouled Aissa",
      "Bouda",
      "Sebaa",
      "Ouled Ahmed Timmi",
    ],
  },
  {
    code: "50",
    name: "Bordj Badji Mokhtar",
    communes: ["Bordj Badji Mokhtar", "Timiaouine", "Tin Zaouatine"],
  },
  {
    code: "51",
    name: "Ouled Djellal",
    communes: ["Ouled Djellal", "Sidi Khaled", "Doucen", "Chaiba"],
  },
  {
    code: "52",
    name: "Béni Abbès",
    communes: [
      "Beni Abbes",
      "Tabelbala",
      "Igli",
      "Kerzaz",
      "Timoudi",
      "Ouled Khoudir",
      "Ksabi",
      "Tamtert",
      "El Ouata",
      "Beni Ikhlef",
    ],
  },
  {
    code: "53",
    name: "In Salah",
    communes: ["In Salah", "In Ghar", "Foggaret Ezzaouia"],
  },
  {
    code: "54",
    name: "In Guezzam",
    communes: ["In Guezzam", "Tin Zaouatine"],
  },
  {
    code: "55",
    name: "Touggourt",
    communes: [
      "Touggourt",
      "Tebesbest",
      "Zaouia El Abidia",
      "El Alia",
      "Taibet",
      "Mnaguer",
      "Blidet Amor",
      "Sidi Slimane",
      "Nezla",
      "El Hadjira",
      "Temacine",
      "Blidet Amor",
      "Megarine",
    ],
  },
  {
    code: "56",
    name: "Djanet",
    communes: ["Djanet", "Bordj El Haoues"],
  },
  {
    code: "57",
    name: "El M'Ghair",
    communes: [
      "El M'Ghair",
      "Djamaa",
      "Sidi Amrane",
      "Oum Touyour",
      "Sidi Khellil",
      "Still",
      "Tendla",
      "El Ogla",
      "Mih Ouansa",
    ],
  },
  {
    code: "58",
    name: "El Meniaa",
    communes: ["El Meniaa", "Hassi Gara", "Hassi Fehal"],
  },
]
